version: "3.8"

services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: your_name
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local